global using System.Text;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.AspNetCore.Mvc;
global using Shreco.Models;
global using AppContext = Shreco.EFDataAccessLibrary.AppContext;
global using Shreco.API.Interfaces;
global using Shreco.API.Services;
global using System.Net;
global using System.Net.Mail;
global using Shreco.API.Data;
global using Microsoft.AspNetCore.Authorization;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text.RegularExpressions;
global using Microsoft.Net.Http.Headers;