// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shreco.EFDataAccessLibrary;

#nullable disable

namespace Shreco.API.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220209081204_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shreco.Models.History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("QrId")
                        .HasColumnType("int");

                    b.Property<int>("WhoAppliedId")
                        .HasColumnType("int");

                    b.Property<int>("WhoUsedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QrId");

                    b.HasIndex("WhoAppliedId");

                    b.HasIndex("WhoUsedId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("Shreco.Models.Qr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ForWhoCreatedId")
                        .HasColumnType("int");

                    b.Property<int>("QrType")
                        .HasColumnType("int");

                    b.Property<int>("WhoCreatedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForWhoCreatedId");

                    b.HasIndex("WhoCreatedId");

                    b.ToTable("Qrs");
                });

            modelBuilder.Entity("Shreco.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameIdentifer")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shreco.Models.History", b =>
                {
                    b.HasOne("Shreco.Models.Qr", "Qr")
                        .WithMany()
                        .HasForeignKey("QrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shreco.Models.User", "WhoApplied")
                        .WithMany("HistoriesWhoApplied")
                        .HasForeignKey("WhoAppliedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shreco.Models.User", "WhoUsed")
                        .WithMany("HistoriesWhoUsed")
                        .HasForeignKey("WhoUsedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Qr");

                    b.Navigation("WhoApplied");

                    b.Navigation("WhoUsed");
                });

            modelBuilder.Entity("Shreco.Models.Qr", b =>
                {
                    b.HasOne("Shreco.Models.User", "ForWhoCreated")
                        .WithMany("QrsForWhoCreated")
                        .HasForeignKey("ForWhoCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Shreco.Models.User", "WhoCreated")
                        .WithMany("QrsWhoCreated")
                        .HasForeignKey("WhoCreatedId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ForWhoCreated");

                    b.Navigation("WhoCreated");
                });

            modelBuilder.Entity("Shreco.Models.User", b =>
                {
                    b.Navigation("HistoriesWhoApplied");

                    b.Navigation("HistoriesWhoUsed");

                    b.Navigation("QrsForWhoCreated");

                    b.Navigation("QrsWhoCreated");
                });
#pragma warning restore 612, 618
        }
    }
}
